### ISSUE TITLE
SR:Function: Verify weights for OF11

### ISSUE THREAD

**Issue by ateucher** [BCWF-Wetlands/wespr#14]
I think the weights for OF11 in SR were wrong in the wsp_calculations spreadsheet. They were 4,3,2,0, but in the Batch Calculator they are 0,1,2,3.

**Comment by ateucher** [comment]
Actually they were lumped (function and benefit had the same values), so I split them, set the `benefit` weights to 4,2,3,0 and the `function` weights to 0,1,2,3

**Comment by gcperk** [comment]
Yes thanks - nice catch Andy. Im happy to close this if it works with you>

**Comment by ateucher** [comment]
Thanks! It will get closed by #16
