### ISSUE TITLE
WS:Function: The calculation for outflow confinement (constric), is different than other indicators

### ISSUE THREAD

**Issue by ateucher** [BCWF-Wetlands/wespr#17]
`(=IF((NoOutlet+NoOutletX>0),"",IF((D75=1),"", MAX(F72:F74)/MAX(E72:E74)))` in WS vs `=IF((NeverWater+TempWet>0),"",IF((NoOutlet+NoOutletX>0),"",IF((D48=1),"",MAX(F45:F47)/MAX(E45:E47))))` in SR and CS

**Comment by gcperk** [comment]
Also not that in PR_fun the calculation is he same as WS and different to SR and CS

**Comment by gcperk** [comment]
confirmed to keep the first version not second
