### ISSUE TITLE
SR:Benefit calculations: rddens3v, disturb3v, rddenswau3v (OF30, OF41, OF42)

### ISSUE THREAD

**Issue by ateucher** [BCWF-Wetlands/wespr#18]
Formula in spreadsheet says if sum(OF30:OF43) == O, NA, else wt_max.(=IF(SUM(OF!D112:OF!D180)=0,"",MAX(F117:F119)/MAX(E117:E119))). The if (sum)... seems like a huge range? Should it just use NoCA?

**Comment by gcperk** [comment]
A BETTER CONDITIONAL FORMULA WOULD LIMIT THE RANGE TO JUST THAT QUESTION AND USE THE SUM FROM COLUMN D RATHER THAN FROM FORM OF.

updated this so all the questions only have the range of the particular question of interest. This will be applied to all the questions with this range.
