### ISSUE TITLE
SR:Benefit formula is incorrect

### ISSUE THREAD

**Issue by ateucher** [BCWF-Wetlands/wespr#20]
The formula in SR: Benefit for topopos3v is wrong (refers to roads). I assume it should be the same as for other indicators (e.g., PR: =IF((OF!D109=""),"",(IF((D123="T"), 5, IF((D123="L"), 4, IF((D123="D"),3, IF((D123="M"), 2, 0)))))/5))

**Comment by gcperk** [comment]
confirmed and fixed
