### ISSUE TITLE
SR:Benefit: Flodist only includes the first three levels of OF10 responses

### ISSUE THREAD

**Issue by ateucher** [BCWF-Wetlands/wespr#21]
Flodist (G9) only includes the first three levels of OF10 responses (MAX(F10:F12)/MAX(E10:E12)). Should this include all six levels as in WS?

**Comment by ateucher** [comment]
Also, most (PR, SR) condition on noCA, while WS does not. Should they all be the same?

**Comment by gcperk** [comment]
confirmed - all levels should be included and removed note from code. No comments provided on the noCA so keeping as is.

**Comment by gcperk** [comment]
Assuming different CA calculations so closing this for now
