### ISSUE TITLE
Add documentation on the process to update weights table. 

### ISSUE THREAD

**Issue by gcperk** [BCWF-Wetlands/wespr#39]
Hi @ateucher. I started working through the PR function and it is nice - although the values also dont match... hmmm. 
I think part of this might be to do with this [issue](https://github.com/BCWF-Wetlands/wespr/issues/38). 

Also -  I updated an error in the weights table and realised I cant tell where this is getting called as part of the wesp site object. I think we should make this more explicit with defaults so users can update weights (and perform sensitivity analysis as needed. Would you be able to add this documentation in the new year. Thanks!

**Comment by ateucher** [comment]
@gcperk sorry I didn't come to this until now! To update the weights table in the package, make the edits in the google doc, and then run the `data-raw/internal-data.R` script. This downloads the data from google docs and and saves the `question_metadat` and `indicator_weightings` as internal data objects in the package. After that, reinstalling/reloading the package should make those data objects up to date. I'll add those instructions to the README.

Re making the weights user-editable on the fly, that would require a different infrastructure set up. So let's chat about what that should look like... most people will just do `remotes::install_github("BCWF-Wetlands/wespr")` and so the workflow above won't work in that case.

**Comment by gcperk** [comment]
@ateucher - Thanks for the update. I am having issues getting this fix to work as it times out while using xl <- drive_find (). I think this is due to my large no of files on gdrive. I think we will need to update this to a separate sheet for future users anyway so perhaps this can be a priority. Happy to chat when you are back on deck.

**Comment by ateucher** [comment]
I think we can replace `drive_find()` with `drive_get()` which should help with the search timeout. I can make this change (and update the internal weights data at the same time)?
