### ISSUE TITLE
Sens : indicator Updates

### ISSUE THREAD

**Issue by gcperk** [BCWF-Wetlands/wespr#42]
fixed - [X ] 1)  update weights table from "sensitivity" to "function" to avoid confusion, check this still works with fun and ben
fixed - [ X] 2) Calculate outmap18 is unclear of calculation (refers to OF40 but shows OF41 in the batch calculation - check calculation 
fixed - [X ] 3) OF24_raresp18 - this is missing the amphibian response. Check calculation 
fixed - [X ] 4) F1- question (woodypct18a) the calculation in G41 references D41 which is no a value cell - should this be D42, D43?
Fixed [X ] 5) F45 acid18 - references D95 from another question entirely. Check this is correct 
Fixed [x ] 6) subscore calculation description contains XXXX, is this missing a component as it doesnt not appear in actual calculation

**Comment by gcperk** [comment]
Fixed all components

**Comment by ateucher** [comment]
@gcperk I also updated `s` to `f` in the all_indicators tab of the WSP_calculations sheet, to match the use of `function` in the weights table
