### ISSUE TITLE
App questions missing from Site object

### ISSUE THREAD

**Issue by gcperk** [BCWF-Wetlands/wespr#46]
@ateucher - I was working through the app ben and fun and seem to be missing this ecosystem from the "used by" list in the site object. Could this be due to the app (three letters?). Although I see the sfts and pol in the used_by list. 

We might want to add an error message if missing data also. ie I tried 

` indicator_data <- get_indicator_data(site, "app")  
and 
indicator_data <- get_indicator_data(site, "ap") and got the same output? '

**Comment by ateucher** [comment]
I think this was basically just a typo in the `indicators()` function that lists the indicators. See #63
