### ISSUE TITLE
POL: funs and bens

### ISSUE THREAD

**Issue by gcperk** [BCWF-Wetlands/wespr#53]
1) imperv16 - function is missing calculations score (OF12)
2) OF32, 36, 37 all contain range from 112 - 180 check this is correct. 
3) Outlet16 and outmap 16 - both reference each other - might need to add an other ifelse to ensure order is correct
3) Get better way to extract final score from indicator
4) Bens - OF32, OF36, OF37 has same spread of values
5) Bens - check F49 is tagged in "used by" POL bens? missing values in this data set

**Comment by gcperk** [comment]
1) updated
2) updated
3) 
3) 
4) Bens - updated 
5) Bens - updated to F50 and added weights

**Comment by ateucher** [comment]
I think I've fixed item 3 in 69b82d9.

**Comment by gcperk** [comment]
Great - closing this off.
