### ISSUE TITLE
FH: funs and bens

### ISSUE THREAD

**Issue by gcperk** [BCWF-Wetlands/wespr#59]
- [x] check range of values for OF30, OF4, OF42, 
- [x] outmap and outdura are in circular functions, add ifelse to check before running order of values. 
- [x] find elegant way to add app score (funs) and wbf score (bens)

**Comment by ateucher** [comment]
@gcperk I think I've fixed the second item (circular reference) in 16dcc6e, have you done the other two?

**Comment by gcperk** [comment]
@completed other checks
