### ISSUE TITLE
POL: fun - the forumla in the formula box differs from description

### ISSUE THREAD

**Issue by ateucher** [BCWF-Wetlands/wespr#76]
Formula: `=10*(IF((AllPermWater=1),0,(3*Pollen+ 2*NestSites + Stress16)/6))`
Description: `(IF((AllPermWater=1),0, ELSE: (3*Pollen+ NestSites +Stress16) /5))`.

May be related to #75 if the 10x is incorrect

**Comment by gcperk** [comment]
fixed this
