### ISSUE TITLE
Clarify Stressor calculations

### ISSUE THREAD

**Issue by gcperk** [BCWF-Wetlands/wespr#85]
Waiting on response for clarification. This will need to be updated in wetflat file also.

**Comment by ateucher** [comment]
Ok, so we shouldn't be doing the stressor sums and subscores in the package? If that's the case, the current wetflat is missing two rows: S6 has eight responses including the the sum and subscore, but it currently only goes to S6_6.

**Comment by gcperk** [comment]
Yes the calculations should be done in the package. I am waiting on how these are actually calculated. I also uploaded a new wetflat file that fixes (some) of the problems and started working through the QA.

**Comment by gcperk** [comment]
I received confirmation that the calculations have not changed since September last year so I am confident these are ones you used from the single calculator @ateucher.
